version: "3.8"

services:
    backend:
        container_name: backend
        image: backend
        build:
            context: .
            dockerfile: app.Dockerfile
        ports:
            - '5000:5000'
        depends_on:
            database:
                condition: service_healthy

    database:
        container_name: database
        image: mysql
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: community
        volumes:
            - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        healthcheck:
             test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
             timeout: 20s
             retries: 10
        restart: always
                                                                                                                                                                                                                                                   